logo: /assets/img/Circle 02.png
title: <p align="center"> Deepak </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/">LinkedIn</a> |
  <a href="https://2023deep.github.io/">GitHub</a>
  
  <br>   
  I'm a Product Manager. Love making business sense out of raw data.
  Working in the Asset Optimization domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
